// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALXxCcMqhY3ExYHsXtDqDQRnpVE1gKJDw',
    appId: '1:41405706416:web:dcd0fb142a047ca3a78b75',
    messagingSenderId: '41405706416',
    projectId: 'daily-diary-97823',
    authDomain: 'daily-diary-97823.firebaseapp.com',
    storageBucket: 'daily-diary-97823.firebasestorage.app',
    measurementId: 'G-F4DC64TWXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0VWCbDShwdf6gb7ZXnQ2n3aOOC8ecxCw',
    appId: '1:41405706416:android:8581c3dcf53b7a94a78b75',
    messagingSenderId: '41405706416',
    projectId: 'daily-diary-97823',
    storageBucket: 'daily-diary-97823.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA22m9usP-pw-d-jZMR37LBONR1SZ92tEE',
    appId: '1:41405706416:ios:c8b074d95650fff3a78b75',
    messagingSenderId: '41405706416',
    projectId: 'daily-diary-97823',
    storageBucket: 'daily-diary-97823.firebasestorage.app',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA22m9usP-pw-d-jZMR37LBONR1SZ92tEE',
    appId: '1:41405706416:ios:c8b074d95650fff3a78b75',
    messagingSenderId: '41405706416',
    projectId: 'daily-diary-97823',
    storageBucket: 'daily-diary-97823.firebasestorage.app',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALXxCcMqhY3ExYHsXtDqDQRnpVE1gKJDw',
    appId: '1:41405706416:web:aaf6f9a8eee24142a78b75',
    messagingSenderId: '41405706416',
    projectId: 'daily-diary-97823',
    authDomain: 'daily-diary-97823.firebaseapp.com',
    storageBucket: 'daily-diary-97823.firebasestorage.app',
    measurementId: 'G-V69549QKQV',
  );
}
